In [1]:
#Writing Herrera et al rules in python language
#meis1 = (meis1 or runx1 or pu1) and not gfi1
#hif1 = (not oxygen and (o2) and not (p53 or foxo3 or ampk)) or (not oxygen and meis1)
#foxo3 = (ampk and (hif1 or p53)) and not (akt or cebpa)
#p53 = hif1 and not (akt or gata1 or pu1)
#gata2 = (gata2 or p53) and not (gata1 or pu1 or gfi1)
#gata1 = (gata1 or gata2 or akt or runx1) and not (pu1 or p53 or ikzf1)
#pu1 = (pu1 or runx1 or (cebpa and ikzf1)) and not (gata1 or gata2 or gfi1)
#cebpa = (pu1 and runx1) and not mef2c
#ikzf1 = (mef2c or ikzf1 or runx1) and not (cebpa or pu1 or gata1)
#gfi1 = (ikzf1 or cebpa) and not (pu1 or p53)
#mef2c = pu1 and not cebpa
#mtor = akt and (not ampk and not p53)
#ampk = (not akt or not oxphos or not hif1) and p53
#akt = h2o2 or not (p53 or foxo3)
#h2o2 = ((gata1 or hif1 or pu1 or oxphos or (sod and o2)) and not antiox)
#o2 = not sod or oxphos
#sod = p53 or foxo3
#antiox = p53 or foxo3
#oxphos = (mtor or akt) and not (foxo3 or hif1)

In [4]:
#Genere gulatory  network with asynchronous updated produced patterns (Figure 3: Herrera et al)
hsc = {"oxygen":0, "runx1":0, "meis1":1, "hif1":1, "foxo3":1, "p53":1, "gata2":1, "gata1":0, "pu1":0, "cebpa":0, "ikzf1":1, "gfi1":0, "mef2c":0, "mtor":0, "ampk":1, "akt":0, "h2o2":0, "o2":0, "sod":1, "antiox":1, "oxphos":0}
mep1 = {"oxygen":0, "runx1":0, "meis1":0, "hif1":1, "foxo3":0, "p53":0, "gata2":0, "gata1":1, "pu1":0, "cebpa":0, "ikzf1":0, "gfi1":0, "mef2c":0, "mtor":1, "ampk":0, "akt":1, "h2o2":1, "o2":1, "sod":0, "antiox":0, "oxphos":0}
mep2 = {"oxygen":0, "runx1":0, "meis1":1, "hif1":1, "foxo3":0, "p53":0, "gata2":0, "gata1":1, "pu1":0, "cebpa":0, "ikzf1":0, "gfi1":0, "mef2c":0, "mtor":1, "ampk":0, "akt":1, "h2o2":1, "o2":1, "sod":0, "antiox":0, "oxphos":0}
mep3 = {"oxygen":0, "runx1":1, "meis1":1, "hif1":1, "foxo3":0, "p53":0, "gata2":0, "gata1":1, "pu1":0, "cebpa":0, "ikzf1":0, "gfi1":0, "mef2c":0, "mtor":1, "ampk":0, "akt":1, "h2o2":1, "o2":1, "sod":0, "antiox":0, "oxphos":0}
mep4 = {"oxygen":1, "runx1":1, "meis1":1, "hif1":0, "foxo3":0, "p53":0, "gata2":0, "gata1":1, "pu1":0, "cebpa":0, "ikzf1":0, "gfi1":0, "mef2c":0, "mtor":1, "ampk":0, "akt":1, "h2o2":1, "o2":1, "sod":0, "antiox":0, "oxphos":1}
mep5 = {"oxygen":1, "runx1":0, "meis1":1, "hif1":0, "foxo3":0, "p53":0, "gata2":0, "gata1":1, "pu1":0, "cebpa":0, "ikzf1":0, "gfi1":0, "mef2c":0, "mtor":1, "ampk":0, "akt":1, "h2o2":1, "o2":1, "sod":0, "antiox":0, "oxphos":1}
mep6 = {"oxygen":1, "runx1":0, "meis1":0, "hif1":0, "foxo3":0, "p53":0, "gata2":0, "gata1":1, "pu1":0, "cebpa":0, "ikzf1":0, "gfi1":0, "mef2c":0, "mtor":1, "ampk":0, "akt":1, "h2o2":1, "o2":1, "sod":0, "antiox":0, "oxphos":1}
gmp1 = {"oxygen":0, "runx1":0, "meis1":1, "hif1":1, "foxo3":0, "p53":0, "gata2":0, "gata1":0, "pu1":1, "cebpa":0, "ikzf1":0, "gfi1":0, "mef2c":1, "mtor":1, "ampk":0, "akt":1, "h2o2":1, "o2":1, "sod":0, "antiox":0, "oxphos":0}
gmp2 = {"oxygen":0, "runx1":1, "meis1":1, "hif1":1, "foxo3":0, "p53":0, "gata2":0, "gata1":0, "pu1":1, "cebpa":1, "ikzf1":0, "gfi1":0, "mef2c":0, "mtor":1, "ampk":0, "akt":1, "h2o2":1, "o2":1, "sod":0, "antiox":0, "oxphos":0}
gmp3 = {"oxygen":1, "runx1":0, "meis1":1, "hif1":0, "foxo3":0, "p53":0, "gata2":0, "gata1":0, "pu1":1, "cebpa":0, "ikzf1":0, "gfi1":0, "mef2c":1, "mtor":1, "ampk":0, "akt":1, "h2o2":1, "o2":1, "sod":0, "antiox":0, "oxphos":1}
gmp4 = {"oxygen":1, "runx1":1, "meis1":1, "hif1":0, "foxo3":0, "p53":0, "gata2":0, "gata1":0, "pu1":1, "cebpa":1, "ikzf1":0, "gfi1":0, "mef2c":0, "mtor":1, "ampk":0, "akt":1, "h2o2":1, "o2":1, "sod":0, "antiox":0, "oxphos":1}
clp1 = {"oxygen":0, "runx1":0, "meis1":0, "hif1":1, "foxo3":0, "p53":0, "gata2":0, "gata1":0, "pu1":0, "cebpa":0, "ikzf1":1, "gfi1":1, "mef2c":0, "mtor":1, "ampk":0, "akt":1, "h2o2":1, "o2":1, "sod":0, "antiox":0, "oxphos":0}
clp2 = {"oxygen":1, "runx1":0, "meis1":0, "hif1":0, "foxo3":0, "p53":0, "gata2":0, "gata1":0, "pu1":0, "cebpa":0, "ikzf1":1, "gfi1":1, "mef2c":0, "mtor":1, "ampk":0, "akt":1, "h2o2":1, "o2":1, "sod":0, "antiox":0, "oxphos":1}

In [ ]:
#Function calculating every node's next value from the current state using the rules declared in the paper
def update_state(cs, fixed=None):
    ns = {}
    ns["oxygen"] = cs["oxygen"]
    ns["runx1"] = int((cs["pu1"] or cs["gata2"] or cs["runx1"]) and not cs["ikzf1"])
    ns["meis1"] = int((cs["meis1"] or cs["runx1"] or cs["pu1"]) and not cs["gfi1"])
    ns["hif1"] = int((not cs["oxygen"] and cs["o2"] and not (cs["p53"] or cs["foxo3"] or cs["ampk"])) or (not cs["oxygen"] and cs["meis1"]))
    ns["foxo3"] = int((cs["ampk"] and (cs["hif1"] or cs["p53"])) and not (cs["akt"] or cs["cebpa"]))
    ns["p53"] = int(cs["hif1"] and not (cs["akt"] or cs["gata1"] or cs["pu1"]))
    ns["gata2"] = int((cs["gata2"] or cs["p53"]) and not (cs["gata1"] or cs["pu1"] or cs["gfi1"]))
    ns["gata1"] = int((cs["gata1"] or cs["gata2"] or cs["akt"] or cs["runx1"]) and not (cs["pu1"] or cs["p53"] or cs["ikzf1"]))
    ns["pu1"] = int((cs["pu1"] or cs["runx1"] or (cs["cebpa"] and cs["ikzf1"])) and not (cs["gata1"] or cs["gata2"] or cs["gfi1"]))
    ns["cebpa"] = int((cs["pu1"] and cs["runx1"]) and not cs["mef2c"])
    ns["ikzf1"] = int((cs["mef2c"] or cs["ikzf1"] or cs["runx1"]) and not (cs["cebpa"] or cs["pu1"] or cs["gata1"]))
    ns["gfi1"] = int((cs["ikzf1"] or cs["cebpa"]) and not (cs["pu1"] or cs["p53"]))
    ns["mef2c"] = int(cs["pu1"] and not cs["cebpa"])
    ns["mtor"] = int(cs["akt"] and not cs["ampk"] and not cs["p53"])
    ns["ampk"] = int((not cs["akt"] or not cs["oxphos"] or not cs["hif1"]) and cs["p53"])
    ns["akt"] = int(cs["h2o2"] or not (cs["p53"] or cs["foxo3"]))
    ns["h2o2"] = int((cs["gata1"] or cs["hif1"] or cs["pu1"] or cs["oxphos"] or (cs["sod"] and cs["o2"])) and not cs["antiox"])
    ns["o2"] = int(not cs["sod"] or cs["oxphos"])
    ns["sod"] = int(cs["p53"] or cs["foxo3"])
    ns["antiox"] = int(cs["p53"] or cs["foxo3"])
    ns["oxphos"] = int((cs["mtor"] or cs["akt"]) and not (cs["foxo3"] or cs["hif1"]))

    if fixed:
        for gene, value in fixed.items():
            ns[gene] = value
    return ns

In [7]:
#Validattion 1: Checking the published cell states

figure_states = {"hsc": hsc, "mep1": mep1, "mep2": mep2, "mep3": mep3,
                 "mep4": mep4, "mep5": mep5, "mep6": mep6,
                 "gmp1": gmp1, "gmp2": gmp2, "gmp3": gmp3, "gmp4": gmp4,
                 "clp1": clp1, "clp2": clp2}

NODES = ["oxygen", "runx1", "meis1", "hif1", "foxo3", "p53", "gata2",
         "gata1", "pu1", "cebpa", "ikzf1", "gfi1", "mef2c", "mtor",
         "ampk", "akt", "h2o2", "o2", "sod", "antiox", "oxphos"]

#Function calculating every node's next value from the current state using the rules declared in the paper
def update_state(cs, fixed=None):
    ns = {}
    ns["oxygen"] = cs["oxygen"]
    ns["runx1"] = int((cs["pu1"] or cs["gata2"] or cs["runx1"]) and not cs["ikzf1"])
    ns["meis1"] = int((cs["meis1"] or cs["runx1"] or cs["pu1"]) and not cs["gfi1"])
    ns["hif1"] = int((not cs["oxygen"] and cs["o2"] and not (cs["p53"] or cs["foxo3"] or cs["ampk"])) or (not cs["oxygen"] and cs["meis1"]))
    ns["foxo3"] = int((cs["ampk"] and (cs["hif1"] or cs["p53"])) and not (cs["akt"] or cs["cebpa"]))
    ns["p53"] = int(cs["hif1"] and not (cs["akt"] or cs["gata1"] or cs["pu1"]))
    ns["gata2"] = int((cs["gata2"] or cs["p53"]) and not (cs["gata1"] or cs["pu1"] or cs["gfi1"]))
    ns["gata1"] = int((cs["gata1"] or cs["gata2"] or cs["akt"] or cs["runx1"]) and not (cs["pu1"] or cs["p53"] or cs["ikzf1"]))
    ns["pu1"] = int((cs["pu1"] or cs["runx1"] or (cs["cebpa"] and cs["ikzf1"])) and not (cs["gata1"] or cs["gata2"] or cs["gfi1"]))
    ns["cebpa"] = int((cs["pu1"] and cs["runx1"]) and not cs["mef2c"])
    ns["ikzf1"] = int((cs["mef2c"] or cs["ikzf1"] or cs["runx1"]) and not (cs["cebpa"] or cs["pu1"] or cs["gata1"]))
    ns["gfi1"] = int((cs["ikzf1"] or cs["cebpa"]) and not (cs["pu1"] or cs["p53"]))
    ns["mef2c"] = int(cs["pu1"] and not cs["cebpa"])
    ns["mtor"] = int(cs["akt"] and not cs["ampk"] and not cs["p53"])
    ns["ampk"] = int((not cs["akt"] or not cs["oxphos"] or not cs["hif1"]) and cs["p53"])
    ns["akt"] = int(cs["h2o2"] or not (cs["p53"] or cs["foxo3"]))
    ns["h2o2"] = int((cs["gata1"] or cs["hif1"] or cs["pu1"] or cs["oxphos"] or (cs["sod"] and cs["o2"])) and not cs["antiox"])
    ns["o2"] = int(not cs["sod"] or cs["oxphos"])
    ns["sod"] = int(cs["p53"] or cs["foxo3"])
    ns["antiox"] = int(cs["p53"] or cs["foxo3"])
    ns["oxphos"] = int((cs["mtor"] or cs["akt"]) and not (cs["foxo3"] or cs["hif1"]))

    if fixed:
        for gene, value in fixed.items():
            ns[gene] = value
    return ns

def check_figure_states():
    for name, state in figure_states.items():
        new_state = update_state(state)
        if new_state == state:
            print(f"{name}: unchanged (fixed point)")
        else:
            changed = [n for n in NODES if new_state[n] != state[n]]
            print(f"{name}: changed at {changed}")

check_figure_states()

hsc: unchanged (fixed point)
mep1: unchanged (fixed point)
mep2: unchanged (fixed point)
mep3: unchanged (fixed point)
mep4: unchanged (fixed point)
mep5: unchanged (fixed point)
mep6: unchanged (fixed point)
gmp1: changed at ['runx1']
gmp2: unchanged (fixed point)
gmp3: changed at ['runx1']
gmp4: unchanged (fixed point)
clp1: unchanged (fixed point)
clp2: unchanged (fixed point)

In [8]:
#Validation 2: Finding the fixed points from scratch
import itertools

NODES = ["oxygen", "runx1", "meis1", "hif1", "foxo3", "p53", "gata2",
         "gata1", "pu1", "cebpa", "ikzf1", "gfi1", "mef2c", "mtor",
         "ampk", "akt", "h2o2", "o2", "sod", "antiox", "oxphos"]


figure_states = {"hsc": hsc, "mep1": mep1, "mep2": mep2, "mep3": mep3,
                 "mep4": mep4, "mep5": mep5, "mep6": mep6,
                 "gmp1": gmp1, "gmp2": gmp2, "gmp3": gmp3, "gmp4": gmp4,
                 "clp1": clp1, "clp2": clp2}

def update_state(cs, fixed=None):
    ns = {}
    ns["oxygen"] = cs["oxygen"]
    ns["runx1"] = int((cs["pu1"] or cs["gata2"] or cs["runx1"]) and not cs["ikzf1"])
    ns["meis1"] = int((cs["meis1"] or cs["runx1"] or cs["pu1"]) and not cs["gfi1"])
    ns["hif1"] = int((not cs["oxygen"] and cs["o2"] and not (cs["p53"] or cs["foxo3"] or cs["ampk"])) or (not cs["oxygen"] and cs["meis1"]))
    ns["foxo3"] = int((cs["ampk"] and (cs["hif1"] or cs["p53"])) and not (cs["akt"] or cs["cebpa"]))
    ns["p53"] = int(cs["hif1"] and not (cs["akt"] or cs["gata1"] or cs["pu1"]))
    ns["gata2"] = int((cs["gata2"] or cs["p53"]) and not (cs["gata1"] or cs["pu1"] or cs["gfi1"]))
    ns["gata1"] = int((cs["gata1"] or cs["gata2"] or cs["akt"] or cs["runx1"]) and not (cs["pu1"] or cs["p53"] or cs["ikzf1"]))
    ns["pu1"] = int((cs["pu1"] or cs["runx1"] or (cs["cebpa"] and cs["ikzf1"])) and not (cs["gata1"] or cs["gata2"] or cs["gfi1"]))
    ns["cebpa"] = int((cs["pu1"] and cs["runx1"]) and not cs["mef2c"])
    ns["ikzf1"] = int((cs["mef2c"] or cs["ikzf1"] or cs["runx1"]) and not (cs["cebpa"] or cs["pu1"] or cs["gata1"]))
    ns["gfi1"] = int((cs["ikzf1"] or cs["cebpa"]) and not (cs["pu1"] or cs["p53"]))
    ns["mef2c"] = int(cs["pu1"] and not cs["cebpa"])
    ns["mtor"] = int(cs["akt"] and not cs["ampk"] and not cs["p53"])
    ns["ampk"] = int((not cs["akt"] or not cs["oxphos"] or not cs["hif1"]) and cs["p53"])
    ns["akt"] = int(cs["h2o2"] or not (cs["p53"] or cs["foxo3"]))
    ns["h2o2"] = int((cs["gata1"] or cs["hif1"] or cs["pu1"] or cs["oxphos"] or (cs["sod"] and cs["o2"])) and not cs["antiox"])
    ns["o2"] = int(not cs["sod"] or cs["oxphos"])
    ns["sod"] = int(cs["p53"] or cs["foxo3"])
    ns["antiox"] = int(cs["p53"] or cs["foxo3"])
    ns["oxphos"] = int((cs["mtor"] or cs["akt"]) and not (cs["foxo3"] or cs["hif1"]))

    if fixed:
        for gene, value in fixed.items():
            ns[gene] = value
    return ns

def find_fixed_points():
    fixed_points = []
    for i, values in enumerate(itertools.product([0, 1], repeat=len(NODES))):
        state = dict(zip(NODES, values))

        
        if update_state(state) == state:
            fixed_points.append(state)

        
        if i % 500000 == 0:
            print(f"Checked {i:,} states, fixed points so far: {len(fixed_points)}")

    print(f"\nTotal fixed points found: {len(fixed_points)}")
    return fixed_points




def cell_state_check(fixed_points):
    for fp in fixed_points:
        exact = [name for name, s in figure_states.items() if s == fp]
        if exact:
            print(f"Exact match: {exact[0]}")
        else:
            # Find the Figure 3 column that differs in the fewest nodes
            name, closest = min(figure_states.items(),
                                key=lambda kv: sum(kv[1][n] != fp[n] for n in NODES))
            differences = [n for n in NODES if closest[n] != fp[n]]
            print(f"No exact match. Closest: {name}, differs at: {differences}")

fixed_attractors = find_fixed_points()
cell_state_check(fixed_attractors)

Checked 0 states, fixed points so far: 0
Checked 500,000 states, fixed points so far: 3
Checked 1,000,000 states, fixed points so far: 7
Checked 1,500,000 states, fixed points so far: 10
Checked 2,000,000 states, fixed points so far: 13

Total fixed points found: 13
Exact match: clp1
Exact match: mep1
Exact match: mep2
Exact match: hsc
No exact match. Closest: gmp1, differs at: ['runx1']
Exact match: gmp2
Exact match: mep3
Exact match: clp2
Exact match: mep6
Exact match: mep5
No exact match. Closest: gmp3, differs at: ['runx1']
Exact match: gmp4
Exact match: mep4

In [2]:
#Validation 3: Basin sizes
#With mutation and wild type combine so the script can take everything together
import itertools
import json
NODES = ["oxygen", "runx1", "meis1", "hif1", "foxo3", "p53", "gata2",
         "gata1", "pu1", "cebpa", "ikzf1", "gfi1", "mef2c", "mtor",
         "ampk", "akt", "h2o2", "o2", "sod", "antiox", "oxphos"]
fixed = [{"foxo3": 0}, {"antiox": 1}, {"mef2c": 0}, {"akt": 1},
         {"meis1": 1}, {"runx1": 1}, {}]
def update_state(cs, fixed=None):
    ns = {}
    ns["oxygen"] = cs["oxygen"]
    ns["runx1"] = int((cs["pu1"] or cs["gata2"] or cs["runx1"]) and not cs["ikzf1"])
    ns["meis1"] = int((cs["meis1"] or cs["runx1"] or cs["pu1"]) and not cs["gfi1"])
    ns["hif1"] = int((not cs["oxygen"] and cs["o2"] and not (cs["p53"] or cs["foxo3"] or cs["ampk"])) or (not cs["oxygen"] and cs["meis1"]))
    ns["foxo3"] = int((cs["ampk"] and (cs["hif1"] or cs["p53"])) and not (cs["akt"] or cs["cebpa"]))
    ns["p53"] = int(cs["hif1"] and not (cs["akt"] or cs["gata1"] or cs["pu1"]))
    ns["gata2"] = int((cs["gata2"] or cs["p53"]) and not (cs["gata1"] or cs["pu1"] or cs["gfi1"]))
    ns["gata1"] = int((cs["gata1"] or cs["gata2"] or cs["akt"] or cs["runx1"]) and not (cs["pu1"] or cs["p53"] or cs["ikzf1"]))
    ns["pu1"] = int((cs["pu1"] or cs["runx1"] or (cs["cebpa"] and cs["ikzf1"])) and not (cs["gata1"] or cs["gata2"] or cs["gfi1"]))
    ns["cebpa"] = int((cs["pu1"] and cs["runx1"]) and not cs["mef2c"])
    ns["ikzf1"] = int((cs["mef2c"] or cs["ikzf1"] or cs["runx1"]) and not (cs["cebpa"] or cs["pu1"] or cs["gata1"]))
    ns["gfi1"] = int((cs["ikzf1"] or cs["cebpa"]) and not (cs["pu1"] or cs["p53"]))
    ns["mef2c"] = int(cs["pu1"] and not cs["cebpa"])
    ns["mtor"] = int(cs["akt"] and not cs["ampk"] and not cs["p53"])
    ns["ampk"] = int((not cs["akt"] or not cs["oxphos"] or not cs["hif1"]) and cs["p53"])
    ns["akt"] = int(cs["h2o2"] or not (cs["p53"] or cs["foxo3"]))
    ns["h2o2"] = int((cs["gata1"] or cs["hif1"] or cs["pu1"] or cs["oxphos"] or (cs["sod"] and cs["o2"])) and not cs["antiox"])
    ns["o2"] = int(not cs["sod"] or cs["oxphos"])
    ns["sod"] = int(cs["p53"] or cs["foxo3"])
    ns["antiox"] = int(cs["p53"] or cs["foxo3"])
    ns["oxphos"] = int((cs["mtor"] or cs["akt"]) and not (cs["foxo3"] or cs["hif1"]))

    if fixed:
        for gene, value in fixed.items():
            ns[gene] = value
    return ns

def to_key(state):
    """Turn a state dictionary into a 0/1 string in NODES order (same format as BoolNet)."""
    return "".join(str(state[n]) for n in NODES)


def boolnet_check(attractors):

    boolnet_counts = [551768, 646816, 54336, 72448, 200808, 91136,   # 6 MEP
                    107096, 107104,                                # 2 CLP
                    36864, 36864, 4096, 4096,                      # 4 GMP
                    3496,                                          # HSC
                    24576, 24576, 53760, 65536, 11776]             # 5 cycles

    if sorted(attractors.values()) == sorted(boolnet_counts):
        print("MATCH: all 18 basin counts equal BoolNet's")
    else:
        print("MISMATCH: basin counts differ from BoolNet's")

def attractor_data(fixed):
    attractors = {}

    for i, values in enumerate(itertools.product([0, 1], repeat=len(NODES))):
        temp_states = []
        state = dict(zip(NODES, values))   # starting state
        #if i % 500000 == 0:
                #print(f"Checked {i:,} states, attractors so far: {len(attractors)}")
        if any(state[g] != v for g, v in fixed.items()):
            continue

        while True:
            temp_states.append(state)
            state = update_state(state, fixed)

            if state in temp_states:
                first = temp_states.index(state)
                attractor_states = temp_states[first:]
                name = "|".join(sorted(to_key(s) for s in attractor_states))

                if name in attractors:
                    attractors[name] += 1
                else:
                    attractors[name] = 1
                break
    print(f"Number of attractors: {len(attractors)}")
    print(f"Total states counted: {sum(attractors.values()):,}")
    return attractors



def cell_type(name):
    """Label an attractor by its marker gene. Cycles (names containing '|') get 'NS'."""
    if "|" in name:
        return "NS"

    # Turn the 0/1 string back into a dictionary so we can check genes by name
    state = dict(zip(NODES, (int(c) for c in name)))

    if state["gata2"]:
        return "HSC"
    if state["gata1"]:
        return "MEP"
    if state["pu1"]:
        return "GMP"
    if state["gfi1"]:
        return "CLP"
    return "unknown"   # safety net: a fixed point with no marker would show up here


def basin_count(attractors, mutation):
    type_counts = {}
    for name, count in attractors.items():
        label = cell_type(name)
        type_counts[label] = type_counts.get(label, 0) + count


    if mutation == True:
        all_total = sum(attractors.values())

        print("\nBasin sizes by cell type (Cycles included, as in the paper):")
        for label in ["HSC", "MEP", "GMP", "CLP", "NS"]:
            count = type_counts.get(label, 0)
            print(f"{label:<4} {count:>10,}   {100 * count / all_total:.3f}%")
            #if label == "NS":
                #print(f"{label:<4} {count:>10,}   included cycles")
            #else:
                #print(f"{label:<4} {count:>10,}   {100 * count / all_total:.3f}%")

        print(f"\nAll states counted: {all_total:,}")
        if "unknown" in type_counts:
            print("Warning: some fixed points had no marker gene active")
    else:
        fate_total = sum(count for label, count in type_counts.items() if label != "NS")
        print("\nBasin sizes by cell type (percentages exclude cycles, as in the paper):")
        for label in ["HSC", "MEP", "GMP", "CLP", "NS"]:
            count = type_counts.get(label, 0)
            if label == "NS":
                print(f"{label:<4} {count:>10,}   excluded (cycles)")
            else:
                print(f"{label:<4} {count:>10,}   {100 * count / fate_total:.2f}%")

        print(f"\nStates reaching a cell fate: {fate_total:,}")
        if "unknown" in type_counts:
            print("Warning: some fixed points had no marker gene active")


for items in fixed:
    if items:
        mutation = True
        temp_key = list(items.keys())
        temp_value = list(items.values())
        print(f"Mutation detected in {temp_key[0]} gene")
        new_item = attractor_data(items)
        basin_calculated = basin_count(new_item, mutation)
        file_name = f"basin_counts_{temp_key[0]}_{temp_value[0]}.json"
    else:
        print("Mutation not detected")
        mutation = False
        new_item = attractor_data(items)
        boolnet_check(new_item)
        basin_calculated = basin_count(new_item, mutation)
        file_name = "basin_counts_wild_type.json"
        
    with open(file_name, "w") as f:
        json.dump(new_item, f, indent=2)

Mutation detected in foxo3 gene
Number of attractors: 18
Total states counted: 1,048,576

Basin sizes by cell type (Cycles included, as in the paper):
HSC         704   0.067%
MEP     821,056   78.302%
GMP      40,960   3.906%
CLP      95,744   9.131%
NS       90,112   8.594%

All states counted: 1,048,576
Mutation detected in antiox gene
Number of attractors: 18
Total states counted: 1,048,576

Basin sizes by cell type (Cycles included, as in the paper):
HSC       3,472   0.331%
MEP     807,136   76.974%
GMP      40,960   3.906%
CLP     106,896   10.194%
NS       90,112   8.594%

All states counted: 1,048,576
Mutation detected in mef2c gene
Number of attractors: 14
Total states counted: 1,048,576

Basin sizes by cell type (Cycles included, as in the paper):
HSC       1,596   0.152%
MEP     794,244   75.745%
GMP      65,536   6.250%
CLP      64,320   6.134%
NS      122,880   11.719%

All states counted: 1,048,576
Mutation detected in akt gene
Number of attractors: 16
Total states counted: 1,048,576

Basin sizes by cell type (Cycles included, as in the paper):
HSC           0   0.000%
MEP     849,920   81.055%
GMP      40,960   3.906%
CLP      67,584   6.445%
NS       90,112   8.594%

All states counted: 1,048,576
Mutation detected in meis1 gene
Number of attractors: 18
Total states counted: 1,048,576

Basin sizes by cell type (Cycles included, as in the paper):
HSC       9,632   0.919%
MEP     682,800   65.117%
GMP      40,960   3.906%
CLP      71,532   6.822%
NS      243,652   23.236%

All states counted: 1,048,576
Mutation detected in runx1 gene
Number of attractors: 16
Total states counted: 1,048,576

Basin sizes by cell type (Cycles included, as in the paper):
HSC         512   0.049%
MEP      83,968   8.008%
GMP      32,768   3.125%
CLP      32,624   3.111%
NS      898,704   85.707%

All states counted: 1,048,576
Mutation not detected
Number of attractors: 18
Total states counted: 2,097,152
MATCH: all 18 basin counts equal BoolNet's

Basin sizes by cell type (percentages exclude cycles, as in the paper):
HSC       3,496   0.18%
MEP   1,617,312   84.37%
GMP      81,920   4.27%
CLP     214,200   11.17%
NS      180,224   excluded (cycles)

States reaching a cell fate: 1,916,928

In [ ]:
# The paper excludes cycles for the wild type but includes them for mutants.
# Here cycles are included in every run, so wild type and mutants share the same denominator.
import itertools
import json
import pandas as pd
NODES = ["oxygen", "runx1", "meis1", "hif1", "foxo3", "p53", "gata2",
         "gata1", "pu1", "cebpa", "ikzf1", "gfi1", "mef2c", "mtor",
         "ampk", "akt", "h2o2", "o2", "sod", "antiox", "oxphos"]
def update_state(cs, fixed=None):
    ns = {}
    ns["oxygen"] = cs["oxygen"]
    ns["runx1"] = int((cs["pu1"] or cs["gata2"] or cs["runx1"]) and not cs["ikzf1"])
    ns["meis1"] = int((cs["meis1"] or cs["runx1"] or cs["pu1"]) and not cs["gfi1"])
    ns["hif1"] = int((not cs["oxygen"] and cs["o2"] and not (cs["p53"] or cs["foxo3"] or cs["ampk"])) or (not cs["oxygen"] and cs["meis1"]))
    ns["foxo3"] = int((cs["ampk"] and (cs["hif1"] or cs["p53"])) and not (cs["akt"] or cs["cebpa"]))
    ns["p53"] = int(cs["hif1"] and not (cs["akt"] or cs["gata1"] or cs["pu1"]))
    ns["gata2"] = int((cs["gata2"] or cs["p53"]) and not (cs["gata1"] or cs["pu1"] or cs["gfi1"]))
    ns["gata1"] = int((cs["gata1"] or cs["gata2"] or cs["akt"] or cs["runx1"]) and not (cs["pu1"] or cs["p53"] or cs["ikzf1"]))
    ns["pu1"] = int((cs["pu1"] or cs["runx1"] or (cs["cebpa"] and cs["ikzf1"])) and not (cs["gata1"] or cs["gata2"] or cs["gfi1"]))
    ns["cebpa"] = int((cs["pu1"] and cs["runx1"]) and not cs["mef2c"])
    ns["ikzf1"] = int((cs["mef2c"] or cs["ikzf1"] or cs["runx1"]) and not (cs["cebpa"] or cs["pu1"] or cs["gata1"]))
    ns["gfi1"] = int((cs["ikzf1"] or cs["cebpa"]) and not (cs["pu1"] or cs["p53"]))
    ns["mef2c"] = int(cs["pu1"] and not cs["cebpa"])
    ns["mtor"] = int(cs["akt"] and not cs["ampk"] and not cs["p53"])
    ns["ampk"] = int((not cs["akt"] or not cs["oxphos"] or not cs["hif1"]) and cs["p53"])
    ns["akt"] = int(cs["h2o2"] or not (cs["p53"] or cs["foxo3"]))
    ns["h2o2"] = int((cs["gata1"] or cs["hif1"] or cs["pu1"] or cs["oxphos"] or (cs["sod"] and cs["o2"])) and not cs["antiox"])
    ns["o2"] = int(not cs["sod"] or cs["oxphos"])
    ns["sod"] = int(cs["p53"] or cs["foxo3"])
    ns["antiox"] = int(cs["p53"] or cs["foxo3"])
    ns["oxphos"] = int((cs["mtor"] or cs["akt"]) and not (cs["foxo3"] or cs["hif1"]))

    if fixed:
        for gene, value in fixed.items():
            ns[gene] = value
    return ns

def to_key(state):
    """Turn a state dictionary into a 0/1 string in NODES order (same format as BoolNet)."""
    return "".join(str(state[n]) for n in NODES)


def attractor_data(fixed):
    attractors = {}

    for i, values in enumerate(itertools.product([0, 1], repeat=len(NODES))):
        temp_states = []
        state = dict(zip(NODES, values))   # starting state
        #if i % 500000 == 0:
                #print(f"Checked {i:,} states, attractors so far: {len(attractors)}")
        if any(state[g] != v for g, v in fixed.items()):
            continue

        while True:
            temp_states.append(state)
            state = update_state(state, fixed)

            if state in temp_states:
                first = temp_states.index(state)
                attractor_states = temp_states[first:]
                name = "|".join(sorted(to_key(s) for s in attractor_states))

                if name in attractors:
                    attractors[name] += 1
                else:
                    attractors[name] = 1
                break
    #print(f"Number of attractors: {len(attractors)}")
    #print(f"Total states counted: {sum(attractors.values()):,}")
    return attractors

def cell_type(name):
    """Label an attractor by its marker gene. Cycles (names containing '|') get 'NS'."""
    if "|" in name:
        return "NS"

    # Turn the 0/1 string back into a dictionary so we can check genes by name
    state = dict(zip(NODES, (int(c) for c in name)))

    if state["gata2"]:
        return "HSC"
    if state["gata1"]:
        return "MEP"
    if state["pu1"]:
        return "GMP"
    if state["gfi1"]:
        return "CLP"
    return "unknown"   # safety net: a fixed point with no marker would show up here


def basin_count(attractors, mutation):
    type_counts = {}
    for name, count in attractors.items():
        label = cell_type(name)
        type_counts[label] = type_counts.get(label, 0) + count
    all_total = sum(attractors.values())
    
    if mutation == True:
        

        print("\nBasin sizes by cell type (Cycles included, as in the paper):")
        for label in ["HSC", "MEP", "GMP", "CLP", "NS"]:
            count = type_counts.get(label, 0)
            print(f"{label:<4} {count:>10,}   {100 * count / all_total:.3f}%")
            #if label == "NS":
                #print(f"{label:<4} {count:>10,}   included cycles")
            #else:
                #print(f"{label:<4} {count:>10,}   {100 * count / all_total:.3f}%")

        print(f"\nAll states counted: {all_total:,}")
        if "unknown" in type_counts:
            print("Warning: some fixed points had no marker gene active")
    else:
        print("\nBasin sizes by cell type (percentages include cycles):")
        for label in ["HSC", "MEP", "GMP", "CLP", "NS"]:
            count = type_counts.get(label, 0)
            print(f"{label:<4} {count:>10,}   {100 * count / all_total:.3f}%")

        print(f"\nAll states counted: {all_total:,}")
        if "unknown" in type_counts:
            print("Warning: some fixed points had no marker gene active")
    return type_counts
    

mutations = [{"foxo3": 0}, {"antiox": 1}, {"mef2c": 0}, {"akt": 1}, {}]
data_dict = {}
for items in mutations:
    if items:
        mutation = True
        temp_key = list(items.keys())
        temp_value = list(items.values())
        print(f"Mutation detected in {temp_key[0]} gene")
        new_item = attractor_data(items)
        basin_calculated = basin_count(new_item, mutation)
        data_dict[temp_key[0]] = basin_calculated
        file_name = f"basin_counts_{temp_key[0]}_{temp_value[0]}.json"
    else:
        print("Mutation not detected")
        mutation = False
        new_item = attractor_data(items)
        basin_calculated = basin_count(new_item, mutation)
        data_dict["wild_type_ci"] = basin_calculated #CI is cycles included
        file_name = "basin_counts_wild_type_cycles_included.json"
        
    #with open(file_name, "w") as f:
        #json.dump(new_item, f, indent=2)     

#Forming table 1 with wild type (cycles included - different from paper)

df = pd.DataFrame.from_dict(data_dict, orient='index')
df = df.fillna(0)
numeric_cols = ["HSC", "MEP", "GMP", "CLP", "NS"]
df = df[numeric_cols]
row_totals = df[numeric_cols].sum(axis=1)

df[numeric_cols] = df[numeric_cols].div(row_totals, axis=0) * 100
df[numeric_cols] = df[numeric_cols].round(3)
df = df.reindex(["wild_type_ci", "foxo3", "antiox", "mef2c", "akt"])
df

Mutation detected in foxo3 gene

Basin sizes by cell type (Cycles included, as in the paper):
HSC         704   0.067%
MEP     821,056   78.302%
GMP      40,960   3.906%
CLP      95,744   9.131%
NS       90,112   8.594%

All states counted: 1,048,576
Mutation detected in antiox gene

Basin sizes by cell type (Cycles included, as in the paper):
HSC       3,472   0.331%
MEP     807,136   76.974%
GMP      40,960   3.906%
CLP     106,896   10.194%
NS       90,112   8.594%

All states counted: 1,048,576
Mutation detected in mef2c gene

Basin sizes by cell type (Cycles included, as in the paper):
HSC       1,596   0.152%
MEP     794,244   75.745%
GMP      65,536   6.250%
CLP      64,320   6.134%
NS      122,880   11.719%

All states counted: 1,048,576
Mutation detected in akt gene

Basin sizes by cell type (Cycles included, as in the paper):
HSC           0   0.000%
MEP     849,920   81.055%
GMP      40,960   3.906%
CLP      67,584   6.445%
NS       90,112   8.594%

All states counted: 1,048,576
Mutation not detected

Basin sizes by cell type (percentages include cycles):
HSC       3,496   0.167%
MEP   1,617,312   77.119%
GMP      81,920   3.906%
CLP     214,200   10.214%
NS      180,224   8.594%

All states counted: 2,097,152

                HSC     MEP    GMP     CLP      NS
wild_type_ci  0.167  77.119  3.906  10.214   8.594
foxo3         0.067  78.302  3.906   9.131   8.594
antiox        0.331  76.974  3.906  10.194   8.594
mef2c         0.152  75.745  6.250   6.134  11.719
akt           0.000  81.055  3.906   6.445   8.594

In [ ]:
import itertools, json, os, hashlib, inspect
import numpy as np, pandas as pd

mutations = [{"foxo3": 0}, {"antiox": 1}, {"mef2c": 0}, {"akt": 1}, {"meis1": 1}, {"runx1": 1}, {}]
CELL_TYPES = ["HSC", "MEP", "GMP", "CLP", "NS"]
NODES = ["oxygen", "runx1", "meis1", "hif1", "foxo3", "p53", "gata2",
         "gata1", "pu1", "cebpa", "ikzf1", "gfi1", "mef2c", "mtor",
         "ampk", "akt", "h2o2", "o2", "sod", "antiox", "oxphos"]

N = len(NODES)
POS = {g: N - 1 - k for k, g in enumerate(NODES)}   # bit position of each node

def update_state(cs, fixed=None):
    ns = {}
    ns["oxygen"] = cs["oxygen"]
    ns["runx1"] = int((cs["pu1"] or cs["gata2"] or cs["runx1"]) and not cs["ikzf1"])
    ns["meis1"] = int((cs["meis1"] or cs["runx1"] or cs["pu1"]) and not cs["gfi1"])
    ns["hif1"] = int((not cs["oxygen"] and cs["o2"] and not (cs["p53"] or cs["foxo3"] or cs["ampk"])) or (not cs["oxygen"] and cs["meis1"]))
    ns["foxo3"] = int((cs["ampk"] and (cs["hif1"] or cs["p53"])) and not (cs["akt"] or cs["cebpa"]))
    ns["p53"] = int(cs["hif1"] and not (cs["akt"] or cs["gata1"] or cs["pu1"]))
    ns["gata2"] = int((cs["gata2"] or cs["p53"]) and not (cs["gata1"] or cs["pu1"] or cs["gfi1"]))
    ns["gata1"] = int((cs["gata1"] or cs["gata2"] or cs["akt"] or cs["runx1"]) and not (cs["pu1"] or cs["p53"] or cs["ikzf1"]))
    ns["pu1"] = int((cs["pu1"] or cs["runx1"] or (cs["cebpa"] and cs["ikzf1"])) and not (cs["gata1"] or cs["gata2"] or cs["gfi1"]))
    ns["cebpa"] = int((cs["pu1"] and cs["runx1"]) and not cs["mef2c"])
    ns["ikzf1"] = int((cs["mef2c"] or cs["ikzf1"] or cs["runx1"]) and not (cs["cebpa"] or cs["pu1"] or cs["gata1"]))
    ns["gfi1"] = int((cs["ikzf1"] or cs["cebpa"]) and not (cs["pu1"] or cs["p53"]))
    ns["mef2c"] = int(cs["pu1"] and not cs["cebpa"])
    ns["mtor"] = int(cs["akt"] and not cs["ampk"] and not cs["p53"])
    ns["ampk"] = int((not cs["akt"] or not cs["oxphos"] or not cs["hif1"]) and cs["p53"])
    ns["akt"] = int(cs["h2o2"] or not (cs["p53"] or cs["foxo3"]))
    ns["h2o2"] = int((cs["gata1"] or cs["hif1"] or cs["pu1"] or cs["oxphos"] or (cs["sod"] and cs["o2"])) and not cs["antiox"])
    ns["o2"] = int(not cs["sod"] or cs["oxphos"])
    ns["sod"] = int(cs["p53"] or cs["foxo3"])
    ns["antiox"] = int(cs["p53"] or cs["foxo3"])
    ns["oxphos"] = int((cs["mtor"] or cs["akt"]) and not (cs["foxo3"] or cs["hif1"]))

    if fixed:
        for gene, value in fixed.items():
            ns[gene] = value
    return ns

def int_to_state(i):
    return {g: (i >> POS[g]) & 1 for g in NODES}

def state_to_int(state):
    n = 0
    for g in NODES:
        n = (n << 1) | state[g]
    return n

def attractor_data(fixed):
    mask = sum(1 << POS[g] for g in fixed)
    val = sum(v << POS[g] for g, v in fixed.items())
    label = np.full(2 ** N, -1, dtype=np.int32)      # attractor id per state
    names, counts = [], []
    for start in range(2 ** N):
        if (start & mask) != val:                    # skip states that contradict the fixed gene
            continue
        if label[start] >= 0:
            counts[int(label[start])] += 1
            continue
        path, seen, s = [], {}, start
        while label[s] < 0 and s not in seen:
            seen[s] = len(path)
            path.append(s)
            s = state_to_int(update_state(int_to_state(s), fixed))
        if label[s] >= 0:
            aid = int(label[s])                      # joined a known attractor
        else:
            cycle = path[seen[s]:]                   # found a new attractor
            names.append("|".join(sorted(format(c, f"0{N}b") for c in cycle)))
            counts.append(0)
            aid = len(names) - 1
        for p in path:
            label[p] = aid
        counts[aid] += 1
    return dict(zip(names, counts))

def cell_type(name):
    """Label an attractor by its marker gene. Cycles (names containing '|') get 'NS'."""
    if "|" in name:
        return "NS"

    # Turn the 0/1 string back into a dictionary so we can check genes by name
    state = dict(zip(NODES, (int(c) for c in name)))

    if state["gata2"]:
        return "HSC"
    if state["gata1"]:
        return "MEP"
    if state["pu1"]:
        return "GMP"
    if state["gfi1"]:
        return "CLP"
    return "unknown"

def basin_count(attractors):
    type_counts = {}
    for name, count in attractors.items():
        label = cell_type(name)
        type_counts[label] = type_counts.get(label, 0) + count
    return type_counts

RULES_HASH = hashlib.md5(inspect.getsource(update_state).encode()).hexdigest()[:8]

def condition_label(fixed):
    if not fixed:
        return "wild_type"
    gene, value = next(iter(fixed.items()))
    return f"{gene}={value}"

def attractor_data_cached(fixed, folder="basin_cache"):
    os.makedirs(folder, exist_ok=True)
    fname = f"{condition_label(fixed).replace('=', '_')}_{RULES_HASH}.json"
    path = os.path.join(folder, fname)
    if os.path.exists(path):
        with open(path) as f:
            return json.load(f)
    result = attractor_data(fixed)
    with open(path, "w") as f:
        json.dump(result, f)
    return result


def create_table(mutations):
    # ---------- 1. simulate each condition and count basins ----------
    results = {}
    for fixed in mutations:
        label = condition_label(fixed)
        counts = basin_count(attractor_data_cached(fixed))
        assert "unknown" not in counts, f"{label}: attractor with no marker gene"
        counts = {c: counts.get(c, 0) for c in CELL_TYPES}
        expected = 2 ** (len(NODES) - len(fixed))
        assert sum(counts.values()) == expected, f"{label}: counted {sum(counts.values())}, expected {expected}"
        results[label] = counts
    results = {"wild_type": results.pop("wild_type"), **results}   # wild type first

    wt = results["wild_type"]
    wt_total = sum(wt.values())
    wt_fate = wt_total - wt["NS"]
    wt_ci = {c: 100 * wt[c] / wt_total for c in CELL_TYPES}                   # cycles included
    wt_ce = {c: 100 * wt[c] / wt_fate for c in CELL_TYPES if c != "NS"}       # cycles excluded

    # ---------- 2. one row per condition x cell type ----------
    rows = []
    for label, counts in results.items():
        total = sum(counts.values())
        fate = total - counts["NS"]
        for c in CELL_TYPES:
            n = counts[c]
            pct_ci = 100 * n / total
            pct_ce = np.nan if c == "NS" else 100 * n / fate
            row = {"Condition": label, "Cell type": c, "Basin size": n,
                   "Percent (CI)": pct_ci, "Percent (CE)": pct_ce,
                   "FC paper (mutant CI / WT CE)": np.nan,
                   "FC CI/CI": np.nan, "FC CE/CE": np.nan}
            if label != "wild_type":
                row["FC CI/CI"] = pct_ci / wt_ci[c]            # NS row shows how much cycles grew
                if c != "NS":
                    row["FC paper (mutant CI / WT CE)"] = pct_ci / wt_ce[c]
                    row["FC CE/CE"] = pct_ce / wt_ce[c]
            rows.append(row)                                    # zero basins give 0.0, not NaN

    df = pd.DataFrame(rows)
    df[df.columns[3:]] = df[df.columns[3:]].round(3)
    return df

def check_half_cycles(df):
    """If a mutant has exactly half the wild-type cycle states, CI/CI must equal CE/CE."""
    ns = df[df["Cell type"] == "NS"].set_index("Condition")["Basin size"]
    for cond in ns.index.drop("wild_type"):
        if 2 * ns[cond] == ns["wild_type"]:
            sub = df[(df["Condition"] == cond) & (df["Cell type"] != "NS")]
            assert np.allclose(sub["FC CI/CI"], sub["FC CE/CE"], atol=2e-3), cond
            print(f"{cond}: CI/CI == CE/CE  OK")


main_df = create_table(mutations)
check_half_cycles(main_df)

# Optional wide views
order = list(main_df["Condition"].unique())
percent_wide = main_df.pivot(index="Condition", columns="Cell type", values="Percent (CI)")[CELL_TYPES].reindex(order)
fold_wide = main_df.pivot(index="Condition", columns="Cell type", values="FC CI/CI")[CELL_TYPES].reindex(order)
main_df

foxo3=0: CI/CI == CE/CE  OK
antiox=1: CI/CI == CE/CE  OK
akt=1: CI/CI == CE/CE  OK

,Condition,Cell type,Basin size,Percent (CI),Percent (CE),FC paper (mutant CI / WT CE),FC CI/CI,FC CE/CE
0,wild_type,HSC,3496,0.167,0.182,NaN,NaN,NaN
1,wild_type,MEP,1617312,77.119,84.370,NaN,NaN,NaN
2,wild_type,GMP,81920,3.906,4.274,NaN,NaN,NaN
3,wild_type,CLP,214200,10.214,11.174,NaN,NaN,NaN
4,wild_type,NS,180224,8.594,NaN,NaN,NaN,NaN
5,foxo3=0,HSC,704,0.067,0.073,0.368,0.403,0.403
6,foxo3=0,MEP,821056,78.302,85.664,0.928,1.015,1.015
7,foxo3=0,GMP,40960,3.906,4.274,0.914,1.000,1.000
8,foxo3=0,CLP,95744,9.131,9.989,0.817,0.894,0.894
9,foxo3=0,NS,90112,8.594,NaN,NaN,1.000,NaN
10,antiox=1,HSC,3472,0.331,0.362,1.816,1.986,1.986
11,antiox=1,MEP,807136,76.974,84.211,0.912,0.998,0.998
12,antiox=1,GMP,40960,3.906,4.274,0.914,1.000,1.000
13,antiox=1,CLP,106896,10.194,11.153,0.912,0.998,0.998
14,antiox=1,NS,90112,8.594,NaN,NaN,1.000,NaN
15,mef2c=0,HSC,1596,0.152,0.172,0.835,0.913,0.945
16,mef2c=0,MEP,794244,75.745,85.800,0.898,0.982,1.017
17,mef2c=0,GMP,65536,6.250,7.080,1.463,1.600,1.657
18,mef2c=0,CLP,64320,6.134,6.948,0.549,0.601,0.622
19,mef2c=0,NS,122880,11.719,NaN,NaN,1.364,NaN
20,akt=1,HSC,0,0.000,0.000,0.000,0.000,0.000
21,akt=1,MEP,849920,81.055,88.675,0.961,1.051,1.051
22,akt=1,GMP,40960,3.906,4.274,0.914,1.000,1.000
23,akt=1,CLP,67584,6.445,7.051,0.577,0.631,0.631
24,akt=1,NS,90112,8.594,NaN,NaN,1.000,NaN
25,meis1=1,HSC,9632,0.919,1.197,5.037,5.510,6.561
26,meis1=1,MEP,682800,65.117,84.828,0.772,0.844,1.005
27,meis1=1,GMP,40960,3.906,5.089,0.914,1.000,1.191
28,meis1=1,CLP,71532,6.822,8.887,0.611,0.668,0.795
29,meis1=1,NS,243652,23.236,NaN,NaN,2.704,NaN
30,runx1=1,HSC,512,0.049,0.342,0.268,0.293,1.873
31,runx1=1,MEP,83968,8.008,56.026,0.095,0.104,0.664
32,runx1=1,GMP,32768,3.125,21.864,0.731,0.800,5.116
33,runx1=1,CLP,32624,3.111,21.768,0.278,0.305,1.948
34,runx1=1,NS,898704,85.707,NaN,NaN,9.973,NaN